package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.AdvertisementInfo;
import com.ruoyi.content.domain.AdvertisementInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AdvertisementInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int countByExample(AdvertisementInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int deleteByExample(AdvertisementInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int deleteByPrimaryKey(Integer adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int insert(AdvertisementInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int insertSelective(AdvertisementInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    List<AdvertisementInfo> selectByExample(AdvertisementInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    AdvertisementInfo selectByPrimaryKey(Integer adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") AdvertisementInfo record, @Param("example") AdvertisementInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByExample(@Param("record") AdvertisementInfo record, @Param("example") AdvertisementInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByPrimaryKeySelective(AdvertisementInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByPrimaryKey(AdvertisementInfo record);
}