package com.ruoyi.content.mapper;


import com.ruoyi.content.domain.ArticlePersonalConfig;
import com.ruoyi.content.domain.ArticlePersonalConfigExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ArticlePersonalConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_personal_config
     *
     * @mbggenerated Wed May 20 09:55:58 CST 2020
     */
    int countByExample(ArticlePersonalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_personal_config
     *
     * @mbggenerated Wed May 20 09:55:58 CST 2020
     */
    int deleteByExample(ArticlePersonalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_personal_config
     *
     * @mbggenerated Wed May 20 09:55:58 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_personal_config
     *
     * @mbggenerated Wed May 20 09:55:58 CST 2020
     */
    int insert(ArticlePersonalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_personal_config
     *
     * @mbggenerated Wed May 20 09:55:58 CST 2020
     */
    int insertSelective(ArticlePersonalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_personal_config
     *
     * @mbggenerated Wed May 20 09:55:58 CST 2020
     */
    List<ArticlePersonalConfig> selectByExample(ArticlePersonalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_personal_config
     *
     * @mbggenerated Wed May 20 09:55:58 CST 2020
     */
    ArticlePersonalConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_personal_config
     *
     * @mbggenerated Wed May 20 09:55:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") ArticlePersonalConfig record, @Param("example") ArticlePersonalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_personal_config
     *
     * @mbggenerated Wed May 20 09:55:58 CST 2020
     */
    int updateByExample(@Param("record") ArticlePersonalConfig record, @Param("example") ArticlePersonalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_personal_config
     *
     * @mbggenerated Wed May 20 09:55:58 CST 2020
     */
    int updateByPrimaryKeySelective(ArticlePersonalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_personal_config
     *
     * @mbggenerated Wed May 20 09:55:58 CST 2020
     */
    int updateByPrimaryKey(ArticlePersonalConfig record);
}