package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.ArticleLabelRelationship;
import com.ruoyi.content.domain.ArticleLabelRelationshipExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ArticleLabelRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label_relationship
     *
     * @mbggenerated
     */
    int countByExample(ArticleLabelRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label_relationship
     *
     * @mbggenerated
     */
    int deleteByExample(ArticleLabelRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label_relationship
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label_relationship
     *
     * @mbggenerated
     */
    int insert(ArticleLabelRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label_relationship
     *
     * @mbggenerated
     */
    int insertSelective(ArticleLabelRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label_relationship
     *
     * @mbggenerated
     */
    List<ArticleLabelRelationship> selectByExample(ArticleLabelRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label_relationship
     *
     * @mbggenerated
     */
    ArticleLabelRelationship selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label_relationship
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ArticleLabelRelationship record, @Param("example") ArticleLabelRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label_relationship
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ArticleLabelRelationship record, @Param("example") ArticleLabelRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label_relationship
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticleLabelRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label_relationship
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleLabelRelationship record);
}