package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.ArticleForwardTrack;
import com.ruoyi.content.domain.ArticleForwardTrackExample;
import com.ruoyi.content.domain.ArticleForwardTrackKey;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ArticleForwardTrackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_forward_track
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    int countByExample(ArticleForwardTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_forward_track
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    int deleteByExample(ArticleForwardTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_forward_track
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    int deleteByPrimaryKey(ArticleForwardTrackKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_forward_track
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    int insert(ArticleForwardTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_forward_track
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    int insertSelective(ArticleForwardTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_forward_track
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    List<ArticleForwardTrack> selectByExample(ArticleForwardTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_forward_track
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    ArticleForwardTrack selectByPrimaryKey(ArticleForwardTrackKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_forward_track
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticleForwardTrack record, @Param("example") ArticleForwardTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_forward_track
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    int updateByExample(@Param("record") ArticleForwardTrack record, @Param("example") ArticleForwardTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_forward_track
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    int updateByPrimaryKeySelective(ArticleForwardTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_forward_track
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    int updateByPrimaryKey(ArticleForwardTrack record);
}