package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.ArticleAdInfo;
import com.ruoyi.content.domain.ArticleAdInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ArticleAdInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_ad_info
     *
     * @mbggenerated Thu Aug 02 14:00:18 CST 2018
     */
    int countByExample(ArticleAdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_ad_info
     *
     * @mbggenerated Thu Aug 02 14:00:18 CST 2018
     */
    int deleteByExample(ArticleAdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_ad_info
     *
     * @mbggenerated Thu Aug 02 14:00:18 CST 2018
     */
    int deleteByPrimaryKey(Integer adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_ad_info
     *
     * @mbggenerated Thu Aug 02 14:00:18 CST 2018
     */
    int insert(ArticleAdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_ad_info
     *
     * @mbggenerated Thu Aug 02 14:00:18 CST 2018
     */
    int insertSelective(ArticleAdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_ad_info
     *
     * @mbggenerated Thu Aug 02 14:00:18 CST 2018
     */
    List<ArticleAdInfo> selectByExample(ArticleAdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_ad_info
     *
     * @mbggenerated Thu Aug 02 14:00:18 CST 2018
     */
    ArticleAdInfo selectByPrimaryKey(Integer adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_ad_info
     *
     * @mbggenerated Thu Aug 02 14:00:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticleAdInfo record, @Param("example") ArticleAdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_ad_info
     *
     * @mbggenerated Thu Aug 02 14:00:18 CST 2018
     */
    int updateByExample(@Param("record") ArticleAdInfo record, @Param("example") ArticleAdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_ad_info
     *
     * @mbggenerated Thu Aug 02 14:00:18 CST 2018
     */
    int updateByPrimaryKeySelective(ArticleAdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_ad_info
     *
     * @mbggenerated Thu Aug 02 14:00:18 CST 2018
     */
    int updateByPrimaryKey(ArticleAdInfo record);
}