package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.ArticleSendUrl;
import com.ruoyi.content.domain.ArticleSendUrlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ArticleSendUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_send_url
     *
     * @mbggenerated Tue Sep 04 17:49:40 CST 2018
     */
    int countByExample(ArticleSendUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_send_url
     *
     * @mbggenerated Tue Sep 04 17:49:40 CST 2018
     */
    int deleteByExample(ArticleSendUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_send_url
     *
     * @mbggenerated Tue Sep 04 17:49:40 CST 2018
     */
    int deleteByPrimaryKey(String publishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_send_url
     *
     * @mbggenerated Tue Sep 04 17:49:40 CST 2018
     */
    int insert(ArticleSendUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_send_url
     *
     * @mbggenerated Tue Sep 04 17:49:40 CST 2018
     */
    int insertSelective(ArticleSendUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_send_url
     *
     * @mbggenerated Tue Sep 04 17:49:40 CST 2018
     */
    List<ArticleSendUrl> selectByExample(ArticleSendUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_send_url
     *
     * @mbggenerated Tue Sep 04 17:49:40 CST 2018
     */
    ArticleSendUrl selectByPrimaryKey(String publishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_send_url
     *
     * @mbggenerated Tue Sep 04 17:49:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticleSendUrl record, @Param("example") ArticleSendUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_send_url
     *
     * @mbggenerated Tue Sep 04 17:49:40 CST 2018
     */
    int updateByExample(@Param("record") ArticleSendUrl record, @Param("example") ArticleSendUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_send_url
     *
     * @mbggenerated Tue Sep 04 17:49:40 CST 2018
     */
    int updateByPrimaryKeySelective(ArticleSendUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_send_url
     *
     * @mbggenerated Tue Sep 04 17:49:40 CST 2018
     */
    int updateByPrimaryKey(ArticleSendUrl record);
}