package com.ruoyi.content.mapper;


import com.ruoyi.content.domain.ArticlePublishSend;
import com.ruoyi.content.domain.ArticlePublishSendExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ArticlePublishSendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_send
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    int countByExample(ArticlePublishSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_send
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    int deleteByExample(ArticlePublishSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_send
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_send
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    int insert(ArticlePublishSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_send
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    int insertSelective(ArticlePublishSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_send
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    List<ArticlePublishSend> selectByExample(ArticlePublishSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_send
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    ArticlePublishSend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_send
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") ArticlePublishSend record, @Param("example") ArticlePublishSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_send
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    int updateByExample(@Param("record") ArticlePublishSend record, @Param("example") ArticlePublishSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_send
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    int updateByPrimaryKeySelective(ArticlePublishSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_send
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    int updateByPrimaryKey(ArticlePublishSend record);
}