package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.ArticleChannel;
import com.ruoyi.content.domain.ArticleChannelExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ArticleChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_channel
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    int countByExample(ArticleChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_channel
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    int deleteByExample(ArticleChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_channel
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_channel
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    int insert(ArticleChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_channel
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    int insertSelective(ArticleChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_channel
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    List<ArticleChannel> selectByExample(ArticleChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_channel
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    ArticleChannel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_channel
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") ArticleChannel record, @Param("example") ArticleChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_channel
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    int updateByExample(@Param("record") ArticleChannel record, @Param("example") ArticleChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_channel
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    int updateByPrimaryKeySelective(ArticleChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_channel
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    int updateByPrimaryKey(ArticleChannel record);
}