package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.AttachmentInfo;
import com.ruoyi.content.domain.AttachmentInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AttachmentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int countByExample(AttachmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int deleteByExample(AttachmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int insert(AttachmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int insertSelective(AttachmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    List<AttachmentInfo> selectByExample(AttachmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    AttachmentInfo selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") AttachmentInfo record, @Param("example") AttachmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByExample(@Param("record") AttachmentInfo record, @Param("example") AttachmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByPrimaryKeySelective(AttachmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByPrimaryKey(AttachmentInfo record);
}