package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.BaseCode;
import com.ruoyi.content.domain.BaseCodeExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface BaseCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_code
     *
     * @mbggenerated Tue Jul 24 14:33:59 CST 2018
     */
    int countByExample(BaseCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_code
     *
     * @mbggenerated Tue Jul 24 14:33:59 CST 2018
     */
    int deleteByExample(BaseCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_code
     *
     * @mbggenerated Tue Jul 24 14:33:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_code
     *
     * @mbggenerated Tue Jul 24 14:33:59 CST 2018
     */
    int insert(BaseCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_code
     *
     * @mbggenerated Tue Jul 24 14:34:00 CST 2018
     */
    int insertSelective(BaseCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_code
     *
     * @mbggenerated Tue Jul 24 14:34:00 CST 2018
     */
    List<BaseCode> selectByExample(BaseCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_code
     *
     * @mbggenerated Tue Jul 24 14:34:00 CST 2018
     */
    BaseCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_code
     *
     * @mbggenerated Tue Jul 24 14:34:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") BaseCode record, @Param("example") BaseCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_code
     *
     * @mbggenerated Tue Jul 24 14:34:00 CST 2018
     */
    int updateByExample(@Param("record") BaseCode record, @Param("example") BaseCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_code
     *
     * @mbggenerated Tue Jul 24 14:34:00 CST 2018
     */
    int updateByPrimaryKeySelective(BaseCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_code
     *
     * @mbggenerated Tue Jul 24 14:34:00 CST 2018
     */
    int updateByPrimaryKey(BaseCode record);
}