package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.CardInfo;
import com.ruoyi.content.domain.CardInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int countByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int deleteByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int deleteByPrimaryKey(Integer cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int insert(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int insertSelective(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    List<CardInfo> selectByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    CardInfo selectByPrimaryKey(Integer cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") CardInfo record, @Param("example") CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByExample(@Param("record") CardInfo record, @Param("example") CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByPrimaryKeySelective(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    int updateByPrimaryKey(CardInfo record);
}