package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.ClickTrackInfo;
import com.ruoyi.content.domain.ClickTrackInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ClickTrackInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    int countByExample(ClickTrackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    int deleteByExample(ClickTrackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    int deleteByPrimaryKey(String clickId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    int insert(ClickTrackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    int insertSelective(ClickTrackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    List<ClickTrackInfo> selectByExampleWithBLOBs(ClickTrackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    List<ClickTrackInfo> selectByExample(ClickTrackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    ClickTrackInfo selectByPrimaryKey(String clickId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") ClickTrackInfo record, @Param("example") ClickTrackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ClickTrackInfo record, @Param("example") ClickTrackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    int updateByExample(@Param("record") ClickTrackInfo record, @Param("example") ClickTrackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    int updateByPrimaryKeySelective(ClickTrackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ClickTrackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_track_info
     *
     * @mbggenerated Wed Jun 20 16:32:59 CST 2018
     */
    int updateByPrimaryKey(ClickTrackInfo record);
}