package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.CmsRoleAuthority;
import com.ruoyi.content.domain.CmsRoleAuthorityExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CmsRoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int countByExample(CmsRoleAuthorityExample
                               example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int deleteByExample(CmsRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int insert(CmsRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int insertSelective(CmsRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    List<CmsRoleAuthority> selectByExample(CmsRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsRoleAuthority record, @Param("example") CmsRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int updateByExample(@Param("record") CmsRoleAuthority record, @Param("example") CmsRoleAuthorityExample example);
}