package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.CmsSysUser;
import com.ruoyi.content.domain.CmsSysUserExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CmsSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_user
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    int countByExample(CmsSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_user
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    int deleteByExample(CmsSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_user
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    int deleteByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_user
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    int insert(CmsSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_user
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    int insertSelective(CmsSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_user
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    List<CmsSysUser> selectByExample(CmsSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_user
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    CmsSysUser selectByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_user
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") CmsSysUser record, @Param("example") CmsSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_user
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    int updateByExample(@Param("record") CmsSysUser record, @Param("example") CmsSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_user
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    int updateByPrimaryKeySelective(CmsSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_user
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    int updateByPrimaryKey(CmsSysUser record);
}