package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.CmsSysRole;
import com.ruoyi.content.domain.CmsSysRoleExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CmsSysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_role
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int countByExample(CmsSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_role
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int deleteByExample(CmsSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_role
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_role
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int insert(CmsSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_role
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int insertSelective(CmsSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_role
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    List<CmsSysRole> selectByExample(CmsSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_role
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    CmsSysRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_role
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsSysRole record, @Param("example") CmsSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_role
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int updateByExample(@Param("record") CmsSysRole record, @Param("example") CmsSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_role
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int updateByPrimaryKeySelective(CmsSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_role
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int updateByPrimaryKey(CmsSysRole record);
}