package com.ruoyi.content.mapper;


import com.ruoyi.content.domain.CmsSysAuthority;
import com.ruoyi.content.domain.CmsSysAuthorityExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CmsSysAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int countByExample(CmsSysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int deleteByExample(CmsSysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int deleteByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int insert(CmsSysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int insertSelective(CmsSysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    List<CmsSysAuthority> selectByExample(CmsSysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    CmsSysAuthority selectByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsSysAuthority record, @Param("example") CmsSysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int updateByExample(@Param("record") CmsSysAuthority record, @Param("example") CmsSysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int updateByPrimaryKeySelective(CmsSysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_sys_authority
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    int updateByPrimaryKey(CmsSysAuthority record);

}