package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.CmsUserRole;
import com.ruoyi.content.domain.CmsUserRoleExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CmsUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbggenerated Fri Aug 18 13:38:42 CST 2017
     */
    int countByExample(CmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbggenerated Fri Aug 18 13:38:42 CST 2017
     */
    int deleteByExample(CmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbggenerated Fri Aug 18 13:38:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbggenerated Fri Aug 18 13:38:42 CST 2017
     */
    int insert(CmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbggenerated Fri Aug 18 13:38:42 CST 2017
     */
    int insertSelective(CmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbggenerated Fri Aug 18 13:38:42 CST 2017
     */
    List<CmsUserRole> selectByExample(CmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbggenerated Fri Aug 18 13:38:42 CST 2017
     */
    CmsUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbggenerated Fri Aug 18 13:38:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsUserRole record, @Param("example") CmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbggenerated Fri Aug 18 13:38:42 CST 2017
     */
    int updateByExample(@Param("record") CmsUserRole record, @Param("example") CmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbggenerated Fri Aug 18 13:38:42 CST 2017
     */
    int updateByPrimaryKeySelective(CmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbggenerated Fri Aug 18 13:38:42 CST 2017
     */
    int updateByPrimaryKey(CmsUserRole record);
}