package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.GalleryPicInfo;
import com.ruoyi.content.domain.GalleryPicInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface GalleryPicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_pic_info
     *
     * @mbggenerated Thu Sep 20 09:57:29 CST 2018
     */
    int countByExample(GalleryPicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_pic_info
     *
     * @mbggenerated Thu Sep 20 09:57:29 CST 2018
     */
    int deleteByExample(GalleryPicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_pic_info
     *
     * @mbggenerated Thu Sep 20 09:57:29 CST 2018
     */
    int deleteByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_pic_info
     *
     * @mbggenerated Thu Sep 20 09:57:29 CST 2018
     */
    int insert(GalleryPicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_pic_info
     *
     * @mbggenerated Thu Sep 20 09:57:29 CST 2018
     */
    int insertSelective(GalleryPicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_pic_info
     *
     * @mbggenerated Thu Sep 20 09:57:29 CST 2018
     */
    List<GalleryPicInfo> selectByExample(GalleryPicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_pic_info
     *
     * @mbggenerated Thu Sep 20 09:57:29 CST 2018
     */
    GalleryPicInfo selectByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_pic_info
     *
     * @mbggenerated Thu Sep 20 09:57:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") GalleryPicInfo record, @Param("example") GalleryPicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_pic_info
     *
     * @mbggenerated Thu Sep 20 09:57:29 CST 2018
     */
    int updateByExample(@Param("record") GalleryPicInfo record, @Param("example") GalleryPicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_pic_info
     *
     * @mbggenerated Thu Sep 20 09:57:29 CST 2018
     */
    int updateByPrimaryKeySelective(GalleryPicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_pic_info
     *
     * @mbggenerated Thu Sep 20 09:57:29 CST 2018
     */
    int updateByPrimaryKey(GalleryPicInfo record);
}