package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.GalleryChannel;
import com.ruoyi.content.domain.GalleryChannelExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface GalleryChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_channel
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    int countByExample(GalleryChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_channel
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    int deleteByExample(GalleryChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_channel
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_channel
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    int insert(GalleryChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_channel
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    int insertSelective(GalleryChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_channel
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    List<GalleryChannel> selectByExample(GalleryChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_channel
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    GalleryChannel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_channel
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") GalleryChannel record, @Param("example") GalleryChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_channel
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    int updateByExample(@Param("record") GalleryChannel record, @Param("example") GalleryChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_channel
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    int updateByPrimaryKeySelective(GalleryChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_channel
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    int updateByPrimaryKey(GalleryChannel record);
}