package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.LdComParty;
import com.ruoyi.content.domain.LdComPartyExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface LdComPartyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcom_party
     *
     * @mbggenerated Tue Sep 25 15:09:32 CST 2018
     */
    int countByExample(LdComPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcom_party
     *
     * @mbggenerated Tue Sep 25 15:09:32 CST 2018
     */
    int deleteByExample(LdComPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcom_party
     *
     * @mbggenerated Tue Sep 25 15:09:32 CST 2018
     */
    int deleteByPrimaryKey(String partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcom_party
     *
     * @mbggenerated Tue Sep 25 15:09:32 CST 2018
     */
    int insert(LdComParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcom_party
     *
     * @mbggenerated Tue Sep 25 15:09:32 CST 2018
     */
    int insertSelective(LdComParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcom_party
     *
     * @mbggenerated Tue Sep 25 15:09:32 CST 2018
     */
    List<LdComParty> selectByExample(LdComPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcom_party
     *
     * @mbggenerated Tue Sep 25 15:09:32 CST 2018
     */
    LdComParty selectByPrimaryKey(String partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcom_party
     *
     * @mbggenerated Tue Sep 25 15:09:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") LdComParty record, @Param("example") LdComPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcom_party
     *
     * @mbggenerated Tue Sep 25 15:09:32 CST 2018
     */
    int updateByExample(@Param("record") LdComParty record, @Param("example") LdComPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcom_party
     *
     * @mbggenerated Tue Sep 25 15:09:32 CST 2018
     */
    int updateByPrimaryKeySelective(LdComParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcom_party
     *
     * @mbggenerated Tue Sep 25 15:09:32 CST 2018
     */
    int updateByPrimaryKey(LdComParty record);
}