package com.ruoyi.content.mapper;

import com.ruoyi.content.domain.PicAdInfo;
import com.ruoyi.content.domain.PicAdInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PicAdInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_ad_info
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    int countByExample(PicAdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_ad_info
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    int deleteByExample(PicAdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_ad_info
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    int deleteByPrimaryKey(Integer picAdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_ad_info
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    int insert(PicAdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_ad_info
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    int insertSelective(PicAdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_ad_info
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    List<PicAdInfo> selectByExample(PicAdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_ad_info
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    PicAdInfo selectByPrimaryKey(Integer picAdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_ad_info
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") PicAdInfo record, @Param("example") PicAdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_ad_info
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    int updateByExample(@Param("record") PicAdInfo record, @Param("example") PicAdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_ad_info
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    int updateByPrimaryKeySelective(PicAdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_ad_info
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    int updateByPrimaryKey(PicAdInfo record);
}