package com.ruoyi.content.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArticlePublishTrackExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    public ArticlePublishTrackExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPublishIdIsNull() {
            addCriterion("PUBLISH_ID is null");
            return (Criteria) this;
        }

        public Criteria andPublishIdIsNotNull() {
            addCriterion("PUBLISH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPublishIdEqualTo(String value) {
            addCriterion("PUBLISH_ID =", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotEqualTo(String value) {
            addCriterion("PUBLISH_ID <>", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdGreaterThan(String value) {
            addCriterion("PUBLISH_ID >", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLISH_ID >=", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdLessThan(String value) {
            addCriterion("PUBLISH_ID <", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdLessThanOrEqualTo(String value) {
            addCriterion("PUBLISH_ID <=", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdLike(String value) {
            addCriterion("PUBLISH_ID like", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotLike(String value) {
            addCriterion("PUBLISH_ID not like", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdIn(List<String> values) {
            addCriterion("PUBLISH_ID in", values, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotIn(List<String> values) {
            addCriterion("PUBLISH_ID not in", values, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdBetween(String value1, String value2) {
            addCriterion("PUBLISH_ID between", value1, value2, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotBetween(String value1, String value2) {
            addCriterion("PUBLISH_ID not between", value1, value2, "publishId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("COMPANY_ID is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("COMPANY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("COMPANY_ID =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("COMPANY_ID <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("COMPANY_ID >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_ID >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("COMPANY_ID <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_ID <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("COMPANY_ID like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("COMPANY_ID not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("COMPANY_ID in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("COMPANY_ID not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("COMPANY_ID between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("COMPANY_ID not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andArticleIdIsNull() {
            addCriterion("ARTICLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andArticleIdIsNotNull() {
            addCriterion("ARTICLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andArticleIdEqualTo(String value) {
            addCriterion("ARTICLE_ID =", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotEqualTo(String value) {
            addCriterion("ARTICLE_ID <>", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThan(String value) {
            addCriterion("ARTICLE_ID >", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThanOrEqualTo(String value) {
            addCriterion("ARTICLE_ID >=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThan(String value) {
            addCriterion("ARTICLE_ID <", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThanOrEqualTo(String value) {
            addCriterion("ARTICLE_ID <=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLike(String value) {
            addCriterion("ARTICLE_ID like", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotLike(String value) {
            addCriterion("ARTICLE_ID not like", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdIn(List<String> values) {
            addCriterion("ARTICLE_ID in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotIn(List<String> values) {
            addCriterion("ARTICLE_ID not in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdBetween(String value1, String value2) {
            addCriterion("ARTICLE_ID between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotBetween(String value1, String value2) {
            addCriterion("ARTICLE_ID not between", value1, value2, "articleId");
            return (Criteria) this;
        }
        
		public Criteria andArticleVersionIsNull() {
			addCriterion("ARTICLE_VERSION is null");
			return (Criteria) this;
		}

		public Criteria andArticleVersionIsNotNull() {
			addCriterion("ARTICLE_VERSION is not null");
			return (Criteria) this;
		}

		public Criteria andArticleVersionEqualTo(String value) {
			addCriterion("ARTICLE_VERSION =", value, "articleVersion");
			return (Criteria) this;
		}

		public Criteria andArticleVersionNotEqualTo(String value) {
			addCriterion("ARTICLE_VERSION <>", value, "articleVersion");
			return (Criteria) this;
		}

		public Criteria andArticleVersionGreaterThan(String value) {
			addCriterion("ARTICLE_VERSION >", value, "articleVersion");
			return (Criteria) this;
		}

		public Criteria andArticleVersionGreaterThanOrEqualTo(String value) {
			addCriterion("ARTICLE_VERSION >=", value, "articleVersion");
			return (Criteria) this;
		}

		public Criteria andArticleVersionLessThan(String value) {
			addCriterion("ARTICLE_VERSION <", value, "articleVersion");
			return (Criteria) this;
		}

		public Criteria andArticleVersionLessThanOrEqualTo(String value) {
			addCriterion("ARTICLE_VERSION <=", value, "articleVersion");
			return (Criteria) this;
		}

		public Criteria andArticleVersionLike(String value) {
			addCriterion("ARTICLE_VERSION like", value, "articleVersion");
			return (Criteria) this;
		}

		public Criteria andArticleVersionNotLike(String value) {
			addCriterion("ARTICLE_VERSION not like", value, "articleVersion");
			return (Criteria) this;
		}

		public Criteria andArticleVersionIn(List<String> values) {
			addCriterion("ARTICLE_VERSION in", values, "articleVersion");
			return (Criteria) this;
		}

		public Criteria andArticleVersionNotIn(List<String> values) {
			addCriterion("ARTICLE_VERSION not in", values, "articleVersion");
			return (Criteria) this;
		}

		public Criteria andArticleVersionBetween(String value1, String value2) {
			addCriterion("ARTICLE_VERSION between", value1, value2, "articleVersion");
			return (Criteria) this;
		}

		public Criteria andArticleVersionNotBetween(String value1, String value2) {
			addCriterion("ARTICLE_VERSION not between", value1, value2, "articleVersion");
			return (Criteria) this;
		}
        
        public Criteria andAdIdIsNull() {
            addCriterion("AD_ID is null");
            return (Criteria) this;
        }

        public Criteria andAdIdIsNotNull() {
            addCriterion("AD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAdIdEqualTo(String value) {
            addCriterion("AD_ID =", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdNotEqualTo(String value) {
            addCriterion("AD_ID <>", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdGreaterThan(String value) {
            addCriterion("AD_ID >", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdGreaterThanOrEqualTo(String value) {
            addCriterion("AD_ID >=", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdLessThan(String value) {
            addCriterion("AD_ID <", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdLessThanOrEqualTo(String value) {
            addCriterion("AD_ID <=", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdLike(String value) {
            addCriterion("AD_ID like", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdNotLike(String value) {
            addCriterion("AD_ID not like", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdIn(List<String> values) {
            addCriterion("AD_ID in", values, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdNotIn(List<String> values) {
            addCriterion("AD_ID not in", values, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdBetween(String value1, String value2) {
            addCriterion("AD_ID between", value1, value2, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdNotBetween(String value1, String value2) {
            addCriterion("AD_ID not between", value1, value2, "adId");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNull() {
            addCriterion("CARD_ID is null");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNotNull() {
            addCriterion("CARD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCardIdEqualTo(String value) {
            addCriterion("CARD_ID =", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotEqualTo(String value) {
            addCriterion("CARD_ID <>", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThan(String value) {
            addCriterion("CARD_ID >", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_ID >=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThan(String value) {
            addCriterion("CARD_ID <", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThanOrEqualTo(String value) {
            addCriterion("CARD_ID <=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLike(String value) {
            addCriterion("CARD_ID like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotLike(String value) {
            addCriterion("CARD_ID not like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdIn(List<String> values) {
            addCriterion("CARD_ID in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotIn(List<String> values) {
            addCriterion("CARD_ID not in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdBetween(String value1, String value2) {
            addCriterion("CARD_ID between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotBetween(String value1, String value2) {
            addCriterion("CARD_ID not between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlIsNull() {
            addCriterion("PUBLISH_VIEW_URL is null");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlIsNotNull() {
            addCriterion("PUBLISH_VIEW_URL is not null");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlEqualTo(String value) {
            addCriterion("PUBLISH_VIEW_URL =", value, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlNotEqualTo(String value) {
            addCriterion("PUBLISH_VIEW_URL <>", value, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlGreaterThan(String value) {
            addCriterion("PUBLISH_VIEW_URL >", value, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLISH_VIEW_URL >=", value, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlLessThan(String value) {
            addCriterion("PUBLISH_VIEW_URL <", value, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlLessThanOrEqualTo(String value) {
            addCriterion("PUBLISH_VIEW_URL <=", value, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlLike(String value) {
            addCriterion("PUBLISH_VIEW_URL like", value, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlNotLike(String value) {
            addCriterion("PUBLISH_VIEW_URL not like", value, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlIn(List<String> values) {
            addCriterion("PUBLISH_VIEW_URL in", values, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlNotIn(List<String> values) {
            addCriterion("PUBLISH_VIEW_URL not in", values, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlBetween(String value1, String value2) {
            addCriterion("PUBLISH_VIEW_URL between", value1, value2, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishViewUrlNotBetween(String value1, String value2) {
            addCriterion("PUBLISH_VIEW_URL not between", value1, value2, "publishViewUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlIsNull() {
            addCriterion("PUBLISH_EDIT_URL is null");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlIsNotNull() {
            addCriterion("PUBLISH_EDIT_URL is not null");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlEqualTo(String value) {
            addCriterion("PUBLISH_EDIT_URL =", value, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlNotEqualTo(String value) {
            addCriterion("PUBLISH_EDIT_URL <>", value, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlGreaterThan(String value) {
            addCriterion("PUBLISH_EDIT_URL >", value, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLISH_EDIT_URL >=", value, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlLessThan(String value) {
            addCriterion("PUBLISH_EDIT_URL <", value, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlLessThanOrEqualTo(String value) {
            addCriterion("PUBLISH_EDIT_URL <=", value, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlLike(String value) {
            addCriterion("PUBLISH_EDIT_URL like", value, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlNotLike(String value) {
            addCriterion("PUBLISH_EDIT_URL not like", value, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlIn(List<String> values) {
            addCriterion("PUBLISH_EDIT_URL in", values, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlNotIn(List<String> values) {
            addCriterion("PUBLISH_EDIT_URL not in", values, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlBetween(String value1, String value2) {
            addCriterion("PUBLISH_EDIT_URL between", value1, value2, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishEditUrlNotBetween(String value1, String value2) {
            addCriterion("PUBLISH_EDIT_URL not between", value1, value2, "publishEditUrl");
            return (Criteria) this;
        }

        public Criteria andPublishStateIsNull() {
            addCriterion("PUBLISH_STATE is null");
            return (Criteria) this;
        }

        public Criteria andPublishStateIsNotNull() {
            addCriterion("PUBLISH_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andPublishStateEqualTo(String value) {
            addCriterion("PUBLISH_STATE =", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateNotEqualTo(String value) {
            addCriterion("PUBLISH_STATE <>", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateGreaterThan(String value) {
            addCriterion("PUBLISH_STATE >", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLISH_STATE >=", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateLessThan(String value) {
            addCriterion("PUBLISH_STATE <", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateLessThanOrEqualTo(String value) {
            addCriterion("PUBLISH_STATE <=", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateLike(String value) {
            addCriterion("PUBLISH_STATE like", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateNotLike(String value) {
            addCriterion("PUBLISH_STATE not like", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateIn(List<String> values) {
            addCriterion("PUBLISH_STATE in", values, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateNotIn(List<String> values) {
            addCriterion("PUBLISH_STATE not in", values, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateBetween(String value1, String value2) {
            addCriterion("PUBLISH_STATE between", value1, value2, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateNotBetween(String value1, String value2) {
            addCriterion("PUBLISH_STATE not between", value1, value2, "publishState");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(String value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(String value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(String value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(String value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLike(String value) {
            addCriterion("UPDATE_DATE like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotLike(String value) {
            addCriterion("UPDATE_DATE not like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<String> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<String> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("UPDATE_TIME like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("UPDATE_TIME not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlIsNull() {
            addCriterion("BACKGROUND_EDIT_URL is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlIsNotNull() {
            addCriterion("BACKGROUND_EDIT_URL is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlEqualTo(String value) {
            addCriterion("BACKGROUND_EDIT_URL =", value, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlNotEqualTo(String value) {
            addCriterion("BACKGROUND_EDIT_URL <>", value, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlGreaterThan(String value) {
            addCriterion("BACKGROUND_EDIT_URL >", value, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlGreaterThanOrEqualTo(String value) {
            addCriterion("BACKGROUND_EDIT_URL >=", value, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlLessThan(String value) {
            addCriterion("BACKGROUND_EDIT_URL <", value, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlLessThanOrEqualTo(String value) {
            addCriterion("BACKGROUND_EDIT_URL <=", value, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlLike(String value) {
            addCriterion("BACKGROUND_EDIT_URL like", value, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlNotLike(String value) {
            addCriterion("BACKGROUND_EDIT_URL not like", value, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlIn(List<String> values) {
            addCriterion("BACKGROUND_EDIT_URL in", values, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlNotIn(List<String> values) {
            addCriterion("BACKGROUND_EDIT_URL not in", values, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlBetween(String value1, String value2) {
            addCriterion("BACKGROUND_EDIT_URL between", value1, value2, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundEditUrlNotBetween(String value1, String value2) {
            addCriterion("BACKGROUND_EDIT_URL not between", value1, value2, "backgroundEditUrl");
            return (Criteria) this;
        }

        public Criteria andLibraryStateIsNull() {
            addCriterion("LIBRARY_STATE is null");
            return (Criteria) this;
        }

        public Criteria andLibraryStateIsNotNull() {
            addCriterion("LIBRARY_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andLibraryStateEqualTo(String value) {
            addCriterion("LIBRARY_STATE =", value, "libraryState");
            return (Criteria) this;
        }

        public Criteria andLibraryStateNotEqualTo(String value) {
            addCriterion("LIBRARY_STATE <>", value, "libraryState");
            return (Criteria) this;
        }

        public Criteria andLibraryStateGreaterThan(String value) {
            addCriterion("LIBRARY_STATE >", value, "libraryState");
            return (Criteria) this;
        }

        public Criteria andLibraryStateGreaterThanOrEqualTo(String value) {
            addCriterion("LIBRARY_STATE >=", value, "libraryState");
            return (Criteria) this;
        }

        public Criteria andLibraryStateLessThan(String value) {
            addCriterion("LIBRARY_STATE <", value, "libraryState");
            return (Criteria) this;
        }

        public Criteria andLibraryStateLessThanOrEqualTo(String value) {
            addCriterion("LIBRARY_STATE <=", value, "libraryState");
            return (Criteria) this;
        }

        public Criteria andLibraryStateLike(String value) {
            addCriterion("LIBRARY_STATE like", value, "libraryState");
            return (Criteria) this;
        }

        public Criteria andLibraryStateNotLike(String value) {
            addCriterion("LIBRARY_STATE not like", value, "libraryState");
            return (Criteria) this;
        }

        public Criteria andLibraryStateIn(List<String> values) {
            addCriterion("LIBRARY_STATE in", values, "libraryState");
            return (Criteria) this;
        }

        public Criteria andLibraryStateNotIn(List<String> values) {
            addCriterion("LIBRARY_STATE not in", values, "libraryState");
            return (Criteria) this;
        }

        public Criteria andLibraryStateBetween(String value1, String value2) {
            addCriterion("LIBRARY_STATE between", value1, value2, "libraryState");
            return (Criteria) this;
        }

        public Criteria andLibraryStateNotBetween(String value1, String value2) {
            addCriterion("LIBRARY_STATE not between", value1, value2, "libraryState");
            return (Criteria) this;
        }
        
		public Criteria andTimestampIsNull() {
			addCriterion("TIMESTAMP is null");
			return (Criteria) this;
		}

		public Criteria andTimestampIsNotNull() {
			addCriterion("TIMESTAMP is not null");
			return (Criteria) this;
		}

		public Criteria andTimestampEqualTo(Date value) {
			addCriterion("TIMESTAMP =", value, "timestamp");
			return (Criteria) this;
		}

		public Criteria andTimestampNotEqualTo(Date value) {
			addCriterion("TIMESTAMP <>", value, "timestamp");
			return (Criteria) this;
		}

		public Criteria andTimestampGreaterThan(Date value) {
			addCriterion("TIMESTAMP >", value, "timestamp");
			return (Criteria) this;
		}

		public Criteria andTimestampGreaterThanOrEqualTo(Date value) {
			addCriterion("TIMESTAMP >=", value, "timestamp");
			return (Criteria) this;
		}

		public Criteria andTimestampLessThan(Date value) {
			addCriterion("TIMESTAMP <", value, "timestamp");
			return (Criteria) this;
		}

		public Criteria andTimestampLessThanOrEqualTo(Date value) {
			addCriterion("TIMESTAMP <=", value, "timestamp");
			return (Criteria) this;
		}

		public Criteria andTimestampIn(List<Date> values) {
			addCriterion("TIMESTAMP in", values, "timestamp");
			return (Criteria) this;
		}

		public Criteria andTimestampNotIn(List<Date> values) {
			addCriterion("TIMESTAMP not in", values, "timestamp");
			return (Criteria) this;
		}

		public Criteria andTimestampBetween(Date value1, Date value2) {
			addCriterion("TIMESTAMP between", value1, value2, "timestamp");
			return (Criteria) this;
		}

		public Criteria andTimestampNotBetween(Date value1, Date value2) {
			addCriterion("TIMESTAMP not between", value1, value2, "timestamp");
			return (Criteria) this;
		}

		public Criteria andAgentCodeIsNull() {
			addCriterion("AGENT_CODE is null");
			return (Criteria) this;
		}

		public Criteria andAgentCodeIsNotNull() {
			addCriterion("AGENT_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andAgentCodeEqualTo(String value) {
			addCriterion("AGENT_CODE =", value, "agentCode");
			return (Criteria) this;
		}

		public Criteria andAgentCodeNotEqualTo(String value) {
			addCriterion("AGENT_CODE <>", value, "agentCode");
			return (Criteria) this;
		}

		public Criteria andAgentCodeGreaterThan(String value) {
			addCriterion("AGENT_CODE >", value, "agentCode");
			return (Criteria) this;
		}

		public Criteria andAgentCodeGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_CODE >=", value, "agentCode");
			return (Criteria) this;
		}

		public Criteria andAgentCodeLessThan(String value) {
			addCriterion("AGENT_CODE <", value, "agentCode");
			return (Criteria) this;
		}

		public Criteria andAgentCodeLessThanOrEqualTo(String value) {
			addCriterion("AGENT_CODE <=", value, "agentCode");
			return (Criteria) this;
		}

		public Criteria andAgentCodeLike(String value) {
			addCriterion("AGENT_CODE like", value, "agentCode");
			return (Criteria) this;
		}

		public Criteria andAgentCodeNotLike(String value) {
			addCriterion("AGENT_CODE not like", value, "agentCode");
			return (Criteria) this;
		}

		public Criteria andAgentCodeIn(List<String> values) {
			addCriterion("AGENT_CODE in", values, "agentCode");
			return (Criteria) this;
		}

		public Criteria andAgentCodeNotIn(List<String> values) {
			addCriterion("AGENT_CODE not in", values, "agentCode");
			return (Criteria) this;
		}

		public Criteria andAgentCodeBetween(String value1, String value2) {
			addCriterion("AGENT_CODE between", value1, value2, "agentCode");
			return (Criteria) this;
		}

		public Criteria andAgentCodeNotBetween(String value1, String value2) {
			addCriterion("AGENT_CODE not between", value1, value2, "agentCode");
			return (Criteria) this;
		}
        
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_publish_track
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 27 10:31:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_publish_track
     *
     * @mbggenerated Fri Jul 27 10:31:00 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}