package com.ruoyi.content.domain;

public class ArticleForwardTrackKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_forward_track.ARTICLE_ID
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_forward_track.FORWARD_TIMESTAMP
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    private String forwardTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_forward_track.USER_ID
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_forward_track.ARTICLE_ID
     *
     * @return the value of article_forward_track.ARTICLE_ID
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_forward_track.ARTICLE_ID
     *
     * @param articleId the value for article_forward_track.ARTICLE_ID
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_forward_track.FORWARD_TIMESTAMP
     *
     * @return the value of article_forward_track.FORWARD_TIMESTAMP
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    public String getForwardTimestamp() {
        return forwardTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_forward_track.FORWARD_TIMESTAMP
     *
     * @param forwardTimestamp the value for article_forward_track.FORWARD_TIMESTAMP
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    public void setForwardTimestamp(String forwardTimestamp) {
        this.forwardTimestamp = forwardTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_forward_track.USER_ID
     *
     * @return the value of article_forward_track.USER_ID
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_forward_track.USER_ID
     *
     * @param userId the value for article_forward_track.USER_ID
     *
     * @mbggenerated Fri Jul 06 14:53:46 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}