package com.ruoyi.content.domain;

public class ArticlePublishSend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.ARTICLE_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.PUBLISH_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private String publishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.SEND_TYPE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private String sendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.GROUP_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.GROUP_NAME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.OPERATE_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private String operateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.OPERATE_NAME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private String operateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.PUBLISH_DATE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private String publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.PUBLISH_TIME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private String publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.OPERATE_DATE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private String operateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.OPERATE_TIME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private String operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_publish_send.SEND_STATE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    private String sendState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.ID
     *
     * @return the value of article_publish_send.ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.ID
     *
     * @param id the value for article_publish_send.ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.ARTICLE_ID
     *
     * @return the value of article_publish_send.ARTICLE_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.ARTICLE_ID
     *
     * @param articleId the value for article_publish_send.ARTICLE_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.PUBLISH_ID
     *
     * @return the value of article_publish_send.PUBLISH_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public String getPublishId() {
        return publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.PUBLISH_ID
     *
     * @param publishId the value for article_publish_send.PUBLISH_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setPublishId(String publishId) {
        this.publishId = publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.SEND_TYPE
     *
     * @return the value of article_publish_send.SEND_TYPE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public String getSendType() {
        return sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.SEND_TYPE
     *
     * @param sendType the value for article_publish_send.SEND_TYPE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setSendType(String sendType) {
        this.sendType = sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.GROUP_ID
     *
     * @return the value of article_publish_send.GROUP_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.GROUP_ID
     *
     * @param groupId the value for article_publish_send.GROUP_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.GROUP_NAME
     *
     * @return the value of article_publish_send.GROUP_NAME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.GROUP_NAME
     *
     * @param groupName the value for article_publish_send.GROUP_NAME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.OPERATE_ID
     *
     * @return the value of article_publish_send.OPERATE_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public String getOperateId() {
        return operateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.OPERATE_ID
     *
     * @param operateId the value for article_publish_send.OPERATE_ID
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setOperateId(String operateId) {
        this.operateId = operateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.OPERATE_NAME
     *
     * @return the value of article_publish_send.OPERATE_NAME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public String getOperateName() {
        return operateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.OPERATE_NAME
     *
     * @param operateName the value for article_publish_send.OPERATE_NAME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setOperateName(String operateName) {
        this.operateName = operateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.PUBLISH_DATE
     *
     * @return the value of article_publish_send.PUBLISH_DATE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.PUBLISH_DATE
     *
     * @param publishDate the value for article_publish_send.PUBLISH_DATE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.PUBLISH_TIME
     *
     * @return the value of article_publish_send.PUBLISH_TIME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.PUBLISH_TIME
     *
     * @param publishTime the value for article_publish_send.PUBLISH_TIME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.OPERATE_DATE
     *
     * @return the value of article_publish_send.OPERATE_DATE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public String getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.OPERATE_DATE
     *
     * @param operateDate the value for article_publish_send.OPERATE_DATE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setOperateDate(String operateDate) {
        this.operateDate = operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.OPERATE_TIME
     *
     * @return the value of article_publish_send.OPERATE_TIME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public String getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.OPERATE_TIME
     *
     * @param operateTime the value for article_publish_send.OPERATE_TIME
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setOperateTime(String operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_publish_send.SEND_STATE
     *
     * @return the value of article_publish_send.SEND_STATE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public String getSendState() {
        return sendState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_publish_send.SEND_STATE
     *
     * @param sendState the value for article_publish_send.SEND_STATE
     *
     * @mbggenerated Thu Jun 04 15:03:08 CST 2020
     */
    public void setSendState(String sendState) {
        this.sendState = sendState;
    }
}