package com.ruoyi.content.domain;

public class ArticleChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.ARTICLE_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.ARTICLE_NAME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String articleName;
    
    private String articleVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.SPECIAL
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String special;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.CHANNEL
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.ARTICLE_STATE
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String articleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.PUBLISH_DATE
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.PUBLISH_TIME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.UPDATE_TIME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.COMPANY_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.BRANCH_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.PUBLISH_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String publishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.ORDER_NO
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_channel.TOP_TIME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    private String topTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.ID
     *
     * @return the value of article_channel.ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.ID
     *
     * @param id the value for article_channel.ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.ARTICLE_ID
     *
     * @return the value of article_channel.ARTICLE_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.ARTICLE_ID
     *
     * @param articleId the value for article_channel.ARTICLE_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.ARTICLE_NAME
     *
     * @return the value of article_channel.ARTICLE_NAME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.ARTICLE_NAME
     *
     * @param articleName the value for article_channel.ARTICLE_NAME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }
    
	public String getArticleVersion() {
		return this.articleVersion;
	}

	public void setArticleVersion(String articleVersion) {
		this.articleVersion = articleVersion;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.SPECIAL
     *
     * @return the value of article_channel.SPECIAL
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getSpecial() {
        return special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.SPECIAL
     *
     * @param special the value for article_channel.SPECIAL
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setSpecial(String special) {
        this.special = special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.CHANNEL
     *
     * @return the value of article_channel.CHANNEL
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.CHANNEL
     *
     * @param channel the value for article_channel.CHANNEL
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.ARTICLE_STATE
     *
     * @return the value of article_channel.ARTICLE_STATE
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getArticleState() {
        return articleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.ARTICLE_STATE
     *
     * @param articleState the value for article_channel.ARTICLE_STATE
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setArticleState(String articleState) {
        this.articleState = articleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.PUBLISH_DATE
     *
     * @return the value of article_channel.PUBLISH_DATE
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.PUBLISH_DATE
     *
     * @param publishDate the value for article_channel.PUBLISH_DATE
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.PUBLISH_TIME
     *
     * @return the value of article_channel.PUBLISH_TIME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.PUBLISH_TIME
     *
     * @param publishTime the value for article_channel.PUBLISH_TIME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.UPDATE_DATE
     *
     * @return the value of article_channel.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.UPDATE_DATE
     *
     * @param updateDate the value for article_channel.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.UPDATE_TIME
     *
     * @return the value of article_channel.UPDATE_TIME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.UPDATE_TIME
     *
     * @param updateTime the value for article_channel.UPDATE_TIME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.COMPANY_ID
     *
     * @return the value of article_channel.COMPANY_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.COMPANY_ID
     *
     * @param companyId the value for article_channel.COMPANY_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.BRANCH_ID
     *
     * @return the value of article_channel.BRANCH_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.BRANCH_ID
     *
     * @param branchId the value for article_channel.BRANCH_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.PUBLISH_ID
     *
     * @return the value of article_channel.PUBLISH_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getPublishId() {
        return publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.PUBLISH_ID
     *
     * @param publishId the value for article_channel.PUBLISH_ID
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setPublishId(String publishId) {
        this.publishId = publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.ORDER_NO
     *
     * @return the value of article_channel.ORDER_NO
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.ORDER_NO
     *
     * @param orderNo the value for article_channel.ORDER_NO
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_channel.TOP_TIME
     *
     * @return the value of article_channel.TOP_TIME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public String getTopTime() {
        return topTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_channel.TOP_TIME
     *
     * @param topTime the value for article_channel.TOP_TIME
     *
     * @mbggenerated Wed Mar 06 16:10:09 CST 2019
     */
    public void setTopTime(String topTime) {
        this.topTime = topTime;
    }
}