package com.ruoyi.content.domain;

public class ArticleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.ARTICLE_ID
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.ARTICLE_NAME
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String articleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.PUSH_DATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String pushDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.ARTICLE_AUTHOR
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String articleAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.ARTICLE_EDIT_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String articleEditUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.ARTICLE_VIEW_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String articleViewUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.LIST_PIC_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String listPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.SPECIAL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String special;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.CHANNEL_ID
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.COMPANY_ID
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.ORIGINAL_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String originalUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.SHARE_IMG_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String shareImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.SHARE_TITLE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String shareTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.ARTICLE_STATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String articleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.SHARE_DES
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String shareDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.CREATE_DATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.CREATE_TIME
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.CREATE_USER
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.UPDATE_DATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.UPDATE_TIME
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.MODIFIED_EDIT_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String modifiedEditUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.MODIFIED_VIEW_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String modifiedViewUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.ARTICLE_CONTENT
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    private String articleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.ARTICLE_ID
     *
     * @return the value of article_info.ARTICLE_ID
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.ARTICLE_ID
     *
     * @param articleId the value for article_info.ARTICLE_ID
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.ARTICLE_NAME
     *
     * @return the value of article_info.ARTICLE_NAME
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.ARTICLE_NAME
     *
     * @param articleName the value for article_info.ARTICLE_NAME
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.PUSH_DATE
     *
     * @return the value of article_info.PUSH_DATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getPushDate() {
        return pushDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.PUSH_DATE
     *
     * @param pushDate the value for article_info.PUSH_DATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setPushDate(String pushDate) {
        this.pushDate = pushDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.ARTICLE_AUTHOR
     *
     * @return the value of article_info.ARTICLE_AUTHOR
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getArticleAuthor() {
        return articleAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.ARTICLE_AUTHOR
     *
     * @param articleAuthor the value for article_info.ARTICLE_AUTHOR
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setArticleAuthor(String articleAuthor) {
        this.articleAuthor = articleAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.ARTICLE_EDIT_URL
     *
     * @return the value of article_info.ARTICLE_EDIT_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getArticleEditUrl() {
        return articleEditUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.ARTICLE_EDIT_URL
     *
     * @param articleEditUrl the value for article_info.ARTICLE_EDIT_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setArticleEditUrl(String articleEditUrl) {
        this.articleEditUrl = articleEditUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.ARTICLE_VIEW_URL
     *
     * @return the value of article_info.ARTICLE_VIEW_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getArticleViewUrl() {
        return articleViewUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.ARTICLE_VIEW_URL
     *
     * @param articleViewUrl the value for article_info.ARTICLE_VIEW_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setArticleViewUrl(String articleViewUrl) {
        this.articleViewUrl = articleViewUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.LIST_PIC_URL
     *
     * @return the value of article_info.LIST_PIC_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getListPicUrl() {
        return listPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.LIST_PIC_URL
     *
     * @param listPicUrl the value for article_info.LIST_PIC_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setListPicUrl(String listPicUrl) {
        this.listPicUrl = listPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.SPECIAL
     *
     * @return the value of article_info.SPECIAL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getSpecial() {
        return special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.SPECIAL
     *
     * @param special the value for article_info.SPECIAL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setSpecial(String special) {
        this.special = special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.CHANNEL_ID
     *
     * @return the value of article_info.CHANNEL_ID
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.CHANNEL_ID
     *
     * @param channelId the value for article_info.CHANNEL_ID
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.COMPANY_ID
     *
     * @return the value of article_info.COMPANY_ID
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.COMPANY_ID
     *
     * @param companyId the value for article_info.COMPANY_ID
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.ORIGINAL_URL
     *
     * @return the value of article_info.ORIGINAL_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getOriginalUrl() {
        return originalUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.ORIGINAL_URL
     *
     * @param originalUrl the value for article_info.ORIGINAL_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.SHARE_IMG_URL
     *
     * @return the value of article_info.SHARE_IMG_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getShareImgUrl() {
        return shareImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.SHARE_IMG_URL
     *
     * @param shareImgUrl the value for article_info.SHARE_IMG_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setShareImgUrl(String shareImgUrl) {
        this.shareImgUrl = shareImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.SHARE_TITLE
     *
     * @return the value of article_info.SHARE_TITLE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getShareTitle() {
        return shareTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.SHARE_TITLE
     *
     * @param shareTitle the value for article_info.SHARE_TITLE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setShareTitle(String shareTitle) {
        this.shareTitle = shareTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.ARTICLE_STATE
     *
     * @return the value of article_info.ARTICLE_STATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getArticleState() {
        return articleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.ARTICLE_STATE
     *
     * @param articleState the value for article_info.ARTICLE_STATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setArticleState(String articleState) {
        this.articleState = articleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.SHARE_DES
     *
     * @return the value of article_info.SHARE_DES
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getShareDes() {
        return shareDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.SHARE_DES
     *
     * @param shareDes the value for article_info.SHARE_DES
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setShareDes(String shareDes) {
        this.shareDes = shareDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.CREATE_DATE
     *
     * @return the value of article_info.CREATE_DATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.CREATE_DATE
     *
     * @param createDate the value for article_info.CREATE_DATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.CREATE_TIME
     *
     * @return the value of article_info.CREATE_TIME
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.CREATE_TIME
     *
     * @param createTime the value for article_info.CREATE_TIME
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.CREATE_USER
     *
     * @return the value of article_info.CREATE_USER
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.CREATE_USER
     *
     * @param createUser the value for article_info.CREATE_USER
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.UPDATE_DATE
     *
     * @return the value of article_info.UPDATE_DATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.UPDATE_DATE
     *
     * @param updateDate the value for article_info.UPDATE_DATE
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.UPDATE_TIME
     *
     * @return the value of article_info.UPDATE_TIME
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.UPDATE_TIME
     *
     * @param updateTime the value for article_info.UPDATE_TIME
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.MODIFIED_EDIT_URL
     *
     * @return the value of article_info.MODIFIED_EDIT_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getModifiedEditUrl() {
        return modifiedEditUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.MODIFIED_EDIT_URL
     *
     * @param modifiedEditUrl the value for article_info.MODIFIED_EDIT_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setModifiedEditUrl(String modifiedEditUrl) {
        this.modifiedEditUrl = modifiedEditUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.MODIFIED_VIEW_URL
     *
     * @return the value of article_info.MODIFIED_VIEW_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getModifiedViewUrl() {
        return modifiedViewUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.MODIFIED_VIEW_URL
     *
     * @param modifiedViewUrl the value for article_info.MODIFIED_VIEW_URL
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setModifiedViewUrl(String modifiedViewUrl) {
        this.modifiedViewUrl = modifiedViewUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.ARTICLE_CONTENT
     *
     * @return the value of article_info.ARTICLE_CONTENT
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.ARTICLE_CONTENT
     *
     * @param articleContent the value for article_info.ARTICLE_CONTENT
     *
     * @mbggenerated Fri May 25 15:02:37 CST 2018
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }
}