package com.ruoyi.content.domain;

public class ArticleLabelRelationship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label_relationship.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label_relationship.ARTICLE_ID
     *
     * @mbggenerated
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label_relationship.LABEL_ID
     *
     * @mbggenerated
     */
    private Integer labelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label_relationship.ID
     *
     * @return the value of article_label_relationship.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label_relationship.ID
     *
     * @param id the value for article_label_relationship.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label_relationship.ARTICLE_ID
     *
     * @return the value of article_label_relationship.ARTICLE_ID
     *
     * @mbggenerated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label_relationship.ARTICLE_ID
     *
     * @param articleId the value for article_label_relationship.ARTICLE_ID
     *
     * @mbggenerated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label_relationship.LABEL_ID
     *
     * @return the value of article_label_relationship.LABEL_ID
     *
     * @mbggenerated
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label_relationship.LABEL_ID
     *
     * @param labelId the value for article_label_relationship.LABEL_ID
     *
     * @mbggenerated
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }
}