package com.ruoyi.content.domain;

import java.util.ArrayList;
import java.util.List;

public class CardInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    public CardInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCardIdIsNull() {
            addCriterion("CARD_ID is null");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNotNull() {
            addCriterion("CARD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCardIdEqualTo(Integer value) {
            addCriterion("CARD_ID =", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotEqualTo(Integer value) {
            addCriterion("CARD_ID <>", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThan(Integer value) {
            addCriterion("CARD_ID >", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CARD_ID >=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThan(Integer value) {
            addCriterion("CARD_ID <", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThanOrEqualTo(Integer value) {
            addCriterion("CARD_ID <=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdIn(List<Integer> values) {
            addCriterion("CARD_ID in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotIn(List<Integer> values) {
            addCriterion("CARD_ID not in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdBetween(Integer value1, Integer value2) {
            addCriterion("CARD_ID between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CARD_ID not between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("COMPANY_ID is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("COMPANY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("COMPANY_ID =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("COMPANY_ID <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("COMPANY_ID >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_ID >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("COMPANY_ID <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_ID <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("COMPANY_ID like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("COMPANY_ID not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("COMPANY_ID in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("COMPANY_ID not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("COMPANY_ID between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("COMPANY_ID not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNull() {
            addCriterion("CARD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNotNull() {
            addCriterion("CARD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCardTypeEqualTo(String value) {
            addCriterion("CARD_TYPE =", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotEqualTo(String value) {
            addCriterion("CARD_TYPE <>", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThan(String value) {
            addCriterion("CARD_TYPE >", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_TYPE >=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThan(String value) {
            addCriterion("CARD_TYPE <", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThanOrEqualTo(String value) {
            addCriterion("CARD_TYPE <=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLike(String value) {
            addCriterion("CARD_TYPE like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotLike(String value) {
            addCriterion("CARD_TYPE not like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeIn(List<String> values) {
            addCriterion("CARD_TYPE in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotIn(List<String> values) {
            addCriterion("CARD_TYPE not in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeBetween(String value1, String value2) {
            addCriterion("CARD_TYPE between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotBetween(String value1, String value2) {
            addCriterion("CARD_TYPE not between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlIsNull() {
            addCriterion("CARD_IMAGE_URL is null");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlIsNotNull() {
            addCriterion("CARD_IMAGE_URL is not null");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlEqualTo(String value) {
            addCriterion("CARD_IMAGE_URL =", value, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlNotEqualTo(String value) {
            addCriterion("CARD_IMAGE_URL <>", value, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlGreaterThan(String value) {
            addCriterion("CARD_IMAGE_URL >", value, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_IMAGE_URL >=", value, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlLessThan(String value) {
            addCriterion("CARD_IMAGE_URL <", value, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlLessThanOrEqualTo(String value) {
            addCriterion("CARD_IMAGE_URL <=", value, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlLike(String value) {
            addCriterion("CARD_IMAGE_URL like", value, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlNotLike(String value) {
            addCriterion("CARD_IMAGE_URL not like", value, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlIn(List<String> values) {
            addCriterion("CARD_IMAGE_URL in", values, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlNotIn(List<String> values) {
            addCriterion("CARD_IMAGE_URL not in", values, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlBetween(String value1, String value2) {
            addCriterion("CARD_IMAGE_URL between", value1, value2, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardImageUrlNotBetween(String value1, String value2) {
            addCriterion("CARD_IMAGE_URL not between", value1, value2, "cardImageUrl");
            return (Criteria) this;
        }

        public Criteria andCardTitleIsNull() {
            addCriterion("CARD_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andCardTitleIsNotNull() {
            addCriterion("CARD_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andCardTitleEqualTo(String value) {
            addCriterion("CARD_TITLE =", value, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardTitleNotEqualTo(String value) {
            addCriterion("CARD_TITLE <>", value, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardTitleGreaterThan(String value) {
            addCriterion("CARD_TITLE >", value, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardTitleGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_TITLE >=", value, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardTitleLessThan(String value) {
            addCriterion("CARD_TITLE <", value, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardTitleLessThanOrEqualTo(String value) {
            addCriterion("CARD_TITLE <=", value, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardTitleLike(String value) {
            addCriterion("CARD_TITLE like", value, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardTitleNotLike(String value) {
            addCriterion("CARD_TITLE not like", value, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardTitleIn(List<String> values) {
            addCriterion("CARD_TITLE in", values, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardTitleNotIn(List<String> values) {
            addCriterion("CARD_TITLE not in", values, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardTitleBetween(String value1, String value2) {
            addCriterion("CARD_TITLE between", value1, value2, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardTitleNotBetween(String value1, String value2) {
            addCriterion("CARD_TITLE not between", value1, value2, "cardTitle");
            return (Criteria) this;
        }

        public Criteria andCardName1IsNull() {
            addCriterion("CARD_NAME1 is null");
            return (Criteria) this;
        }

        public Criteria andCardName1IsNotNull() {
            addCriterion("CARD_NAME1 is not null");
            return (Criteria) this;
        }

        public Criteria andCardName1EqualTo(String value) {
            addCriterion("CARD_NAME1 =", value, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName1NotEqualTo(String value) {
            addCriterion("CARD_NAME1 <>", value, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName1GreaterThan(String value) {
            addCriterion("CARD_NAME1 >", value, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName1GreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NAME1 >=", value, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName1LessThan(String value) {
            addCriterion("CARD_NAME1 <", value, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName1LessThanOrEqualTo(String value) {
            addCriterion("CARD_NAME1 <=", value, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName1Like(String value) {
            addCriterion("CARD_NAME1 like", value, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName1NotLike(String value) {
            addCriterion("CARD_NAME1 not like", value, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName1In(List<String> values) {
            addCriterion("CARD_NAME1 in", values, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName1NotIn(List<String> values) {
            addCriterion("CARD_NAME1 not in", values, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName1Between(String value1, String value2) {
            addCriterion("CARD_NAME1 between", value1, value2, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName1NotBetween(String value1, String value2) {
            addCriterion("CARD_NAME1 not between", value1, value2, "cardName1");
            return (Criteria) this;
        }

        public Criteria andCardName2IsNull() {
            addCriterion("CARD_NAME2 is null");
            return (Criteria) this;
        }

        public Criteria andCardName2IsNotNull() {
            addCriterion("CARD_NAME2 is not null");
            return (Criteria) this;
        }

        public Criteria andCardName2EqualTo(String value) {
            addCriterion("CARD_NAME2 =", value, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardName2NotEqualTo(String value) {
            addCriterion("CARD_NAME2 <>", value, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardName2GreaterThan(String value) {
            addCriterion("CARD_NAME2 >", value, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardName2GreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NAME2 >=", value, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardName2LessThan(String value) {
            addCriterion("CARD_NAME2 <", value, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardName2LessThanOrEqualTo(String value) {
            addCriterion("CARD_NAME2 <=", value, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardName2Like(String value) {
            addCriterion("CARD_NAME2 like", value, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardName2NotLike(String value) {
            addCriterion("CARD_NAME2 not like", value, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardName2In(List<String> values) {
            addCriterion("CARD_NAME2 in", values, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardName2NotIn(List<String> values) {
            addCriterion("CARD_NAME2 not in", values, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardName2Between(String value1, String value2) {
            addCriterion("CARD_NAME2 between", value1, value2, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardName2NotBetween(String value1, String value2) {
            addCriterion("CARD_NAME2 not between", value1, value2, "cardName2");
            return (Criteria) this;
        }

        public Criteria andCardLink1IsNull() {
            addCriterion("CARD_LINK1 is null");
            return (Criteria) this;
        }

        public Criteria andCardLink1IsNotNull() {
            addCriterion("CARD_LINK1 is not null");
            return (Criteria) this;
        }

        public Criteria andCardLink1EqualTo(String value) {
            addCriterion("CARD_LINK1 =", value, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink1NotEqualTo(String value) {
            addCriterion("CARD_LINK1 <>", value, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink1GreaterThan(String value) {
            addCriterion("CARD_LINK1 >", value, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink1GreaterThanOrEqualTo(String value) {
            addCriterion("CARD_LINK1 >=", value, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink1LessThan(String value) {
            addCriterion("CARD_LINK1 <", value, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink1LessThanOrEqualTo(String value) {
            addCriterion("CARD_LINK1 <=", value, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink1Like(String value) {
            addCriterion("CARD_LINK1 like", value, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink1NotLike(String value) {
            addCriterion("CARD_LINK1 not like", value, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink1In(List<String> values) {
            addCriterion("CARD_LINK1 in", values, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink1NotIn(List<String> values) {
            addCriterion("CARD_LINK1 not in", values, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink1Between(String value1, String value2) {
            addCriterion("CARD_LINK1 between", value1, value2, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink1NotBetween(String value1, String value2) {
            addCriterion("CARD_LINK1 not between", value1, value2, "cardLink1");
            return (Criteria) this;
        }

        public Criteria andCardLink2IsNull() {
            addCriterion("CARD_LINK2 is null");
            return (Criteria) this;
        }

        public Criteria andCardLink2IsNotNull() {
            addCriterion("CARD_LINK2 is not null");
            return (Criteria) this;
        }

        public Criteria andCardLink2EqualTo(String value) {
            addCriterion("CARD_LINK2 =", value, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardLink2NotEqualTo(String value) {
            addCriterion("CARD_LINK2 <>", value, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardLink2GreaterThan(String value) {
            addCriterion("CARD_LINK2 >", value, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardLink2GreaterThanOrEqualTo(String value) {
            addCriterion("CARD_LINK2 >=", value, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardLink2LessThan(String value) {
            addCriterion("CARD_LINK2 <", value, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardLink2LessThanOrEqualTo(String value) {
            addCriterion("CARD_LINK2 <=", value, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardLink2Like(String value) {
            addCriterion("CARD_LINK2 like", value, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardLink2NotLike(String value) {
            addCriterion("CARD_LINK2 not like", value, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardLink2In(List<String> values) {
            addCriterion("CARD_LINK2 in", values, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardLink2NotIn(List<String> values) {
            addCriterion("CARD_LINK2 not in", values, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardLink2Between(String value1, String value2) {
            addCriterion("CARD_LINK2 between", value1, value2, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardLink2NotBetween(String value1, String value2) {
            addCriterion("CARD_LINK2 not between", value1, value2, "cardLink2");
            return (Criteria) this;
        }

        public Criteria andCardStateIsNull() {
            addCriterion("CARD_STATE is null");
            return (Criteria) this;
        }

        public Criteria andCardStateIsNotNull() {
            addCriterion("CARD_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andCardStateEqualTo(String value) {
            addCriterion("CARD_STATE =", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateNotEqualTo(String value) {
            addCriterion("CARD_STATE <>", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateGreaterThan(String value) {
            addCriterion("CARD_STATE >", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_STATE >=", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateLessThan(String value) {
            addCriterion("CARD_STATE <", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateLessThanOrEqualTo(String value) {
            addCriterion("CARD_STATE <=", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateLike(String value) {
            addCriterion("CARD_STATE like", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateNotLike(String value) {
            addCriterion("CARD_STATE not like", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateIn(List<String> values) {
            addCriterion("CARD_STATE in", values, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateNotIn(List<String> values) {
            addCriterion("CARD_STATE not in", values, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateBetween(String value1, String value2) {
            addCriterion("CARD_STATE between", value1, value2, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateNotBetween(String value1, String value2) {
            addCriterion("CARD_STATE not between", value1, value2, "cardState");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(String value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(String value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(String value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(String value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLike(String value) {
            addCriterion("UPDATE_DATE like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotLike(String value) {
            addCriterion("UPDATE_DATE not like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<String> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<String> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("UPDATE_TIME like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("UPDATE_TIME not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 26 15:46:22 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card_info
     *
     * @mbggenerated Mon Mar 26 15:46:22 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}