package com.ruoyi.content.domain;

public class CmsSysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.EMAIL
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.OPEN_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.PWD
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.SALT
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.USER_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.JOB_NUMBER
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String jobNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.COMPANY_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.BRANCH_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.NAME
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.SEX
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.PHONE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.STATE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.CREATE_USER
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.CREATE_DATE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.CREATE_TIME
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.UPDATE_USER
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.UPDATE_DATE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_user.UPDATE_REMARK
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    private String updateRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.EMAIL
     *
     * @return the value of cms_sys_user.EMAIL
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.EMAIL
     *
     * @param email the value for cms_sys_user.EMAIL
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.OPEN_ID
     *
     * @return the value of cms_sys_user.OPEN_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.OPEN_ID
     *
     * @param openId the value for cms_sys_user.OPEN_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.PWD
     *
     * @return the value of cms_sys_user.PWD
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.PWD
     *
     * @param pwd the value for cms_sys_user.PWD
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.SALT
     *
     * @return the value of cms_sys_user.SALT
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.SALT
     *
     * @param salt the value for cms_sys_user.SALT
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.USER_ID
     *
     * @return the value of cms_sys_user.USER_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.USER_ID
     *
     * @param userId the value for cms_sys_user.USER_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.JOB_NUMBER
     *
     * @return the value of cms_sys_user.JOB_NUMBER
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.JOB_NUMBER
     *
     * @param jobNumber the value for cms_sys_user.JOB_NUMBER
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.COMPANY_ID
     *
     * @return the value of cms_sys_user.COMPANY_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.COMPANY_ID
     *
     * @param companyId the value for cms_sys_user.COMPANY_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.BRANCH_ID
     *
     * @return the value of cms_sys_user.BRANCH_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.BRANCH_ID
     *
     * @param branchId the value for cms_sys_user.BRANCH_ID
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.NAME
     *
     * @return the value of cms_sys_user.NAME
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.NAME
     *
     * @param name the value for cms_sys_user.NAME
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.SEX
     *
     * @return the value of cms_sys_user.SEX
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.SEX
     *
     * @param sex the value for cms_sys_user.SEX
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.PHONE
     *
     * @return the value of cms_sys_user.PHONE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.PHONE
     *
     * @param phone the value for cms_sys_user.PHONE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.STATE
     *
     * @return the value of cms_sys_user.STATE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.STATE
     *
     * @param state the value for cms_sys_user.STATE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.CREATE_USER
     *
     * @return the value of cms_sys_user.CREATE_USER
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.CREATE_USER
     *
     * @param createUser the value for cms_sys_user.CREATE_USER
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.CREATE_DATE
     *
     * @return the value of cms_sys_user.CREATE_DATE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.CREATE_DATE
     *
     * @param createDate the value for cms_sys_user.CREATE_DATE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.CREATE_TIME
     *
     * @return the value of cms_sys_user.CREATE_TIME
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.CREATE_TIME
     *
     * @param createTime the value for cms_sys_user.CREATE_TIME
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.UPDATE_USER
     *
     * @return the value of cms_sys_user.UPDATE_USER
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.UPDATE_USER
     *
     * @param updateUser the value for cms_sys_user.UPDATE_USER
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.UPDATE_DATE
     *
     * @return the value of cms_sys_user.UPDATE_DATE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.UPDATE_DATE
     *
     * @param updateDate the value for cms_sys_user.UPDATE_DATE
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.UPDATE_TIME
     *
     * @return the value of cms_sys_user.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.UPDATE_TIME
     *
     * @param updateTime the value for cms_sys_user.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_user.UPDATE_REMARK
     *
     * @return the value of cms_sys_user.UPDATE_REMARK
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public String getUpdateRemark() {
        return updateRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_user.UPDATE_REMARK
     *
     * @param updateRemark the value for cms_sys_user.UPDATE_REMARK
     *
     * @mbggenerated Tue Aug 28 09:28:51 CST 2018
     */
    public void setUpdateRemark(String updateRemark) {
        this.updateRemark = updateRemark;
    }
}