package com.ruoyi.content.domain;

public class CmsSysAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.NUM
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.ID
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.LEVEL
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.TYPE
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.OPERATOR_ROLE_NAME
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private String operatorRoleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.OPERATOR_ROLE_PATH
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private String operatorRolePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.CREATE_DATE
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.CREATE_TIME
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.CREATE_USER
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.UPDATE_DATE
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_sys_authority.UPDATE_USER
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.NUM
     *
     * @return the value of cms_sys_authority.NUM
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.NUM
     *
     * @param num the value for cms_sys_authority.NUM
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.ID
     *
     * @return the value of cms_sys_authority.ID
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.ID
     *
     * @param id the value for cms_sys_authority.ID
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.LEVEL
     *
     * @return the value of cms_sys_authority.LEVEL
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.LEVEL
     *
     * @param level the value for cms_sys_authority.LEVEL
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.TYPE
     *
     * @return the value of cms_sys_authority.TYPE
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.TYPE
     *
     * @param type the value for cms_sys_authority.TYPE
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.OPERATOR_ROLE_NAME
     *
     * @return the value of cms_sys_authority.OPERATOR_ROLE_NAME
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public String getOperatorRoleName() {
        return operatorRoleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.OPERATOR_ROLE_NAME
     *
     * @param operatorRoleName the value for cms_sys_authority.OPERATOR_ROLE_NAME
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setOperatorRoleName(String operatorRoleName) {
        this.operatorRoleName = operatorRoleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.OPERATOR_ROLE_PATH
     *
     * @return the value of cms_sys_authority.OPERATOR_ROLE_PATH
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public String getOperatorRolePath() {
        return operatorRolePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.OPERATOR_ROLE_PATH
     *
     * @param operatorRolePath the value for cms_sys_authority.OPERATOR_ROLE_PATH
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setOperatorRolePath(String operatorRolePath) {
        this.operatorRolePath = operatorRolePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.CREATE_DATE
     *
     * @return the value of cms_sys_authority.CREATE_DATE
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.CREATE_DATE
     *
     * @param createDate the value for cms_sys_authority.CREATE_DATE
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.CREATE_TIME
     *
     * @return the value of cms_sys_authority.CREATE_TIME
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.CREATE_TIME
     *
     * @param createTime the value for cms_sys_authority.CREATE_TIME
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.CREATE_USER
     *
     * @return the value of cms_sys_authority.CREATE_USER
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.CREATE_USER
     *
     * @param createUser the value for cms_sys_authority.CREATE_USER
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.UPDATE_DATE
     *
     * @return the value of cms_sys_authority.UPDATE_DATE
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.UPDATE_DATE
     *
     * @param updateDate the value for cms_sys_authority.UPDATE_DATE
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.UPDATE_TIME
     *
     * @return the value of cms_sys_authority.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.UPDATE_TIME
     *
     * @param updateTime the value for cms_sys_authority.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sys_authority.UPDATE_USER
     *
     * @return the value of cms_sys_authority.UPDATE_USER
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sys_authority.UPDATE_USER
     *
     * @param updateUser the value for cms_sys_authority.UPDATE_USER
     *
     * @mbggenerated Thu Aug 17 17:24:12 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
}