package com.ruoyi.content.domain;

public class GalleryChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery_channel.ID
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery_channel.PIC_ID
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    private Integer picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery_channel.SPECIAL
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    private String special;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery_channel.CHANNEL_ID
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery_channel.STATE
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery_channel.CREATE_DATE
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery_channel.CREATE_TIME
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery_channel.COMPANY_ID
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery_channel.BRANCH_ID
     *
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    private String branchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery_channel.ID
     *
     * @return the value of gallery_channel.ID
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery_channel.ID
     *
     * @param id the value for gallery_channel.ID
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery_channel.PIC_ID
     *
     * @return the value of gallery_channel.PIC_ID
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery_channel.PIC_ID
     *
     * @param picId the value for gallery_channel.PIC_ID
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery_channel.SPECIAL
     *
     * @return the value of gallery_channel.SPECIAL
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public String getSpecial() {
        return special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery_channel.SPECIAL
     *
     * @param special the value for gallery_channel.SPECIAL
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public void setSpecial(String special) {
        this.special = special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery_channel.CHANNEL_ID
     *
     * @return the value of gallery_channel.CHANNEL_ID
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery_channel.CHANNEL_ID
     *
     * @param channelId the value for gallery_channel.CHANNEL_ID
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery_channel.STATE
     *
     * @return the value of gallery_channel.STATE
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery_channel.STATE
     *
     * @param state the value for gallery_channel.STATE
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery_channel.CREATE_DATE
     *
     * @return the value of gallery_channel.CREATE_DATE
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery_channel.CREATE_DATE
     *
     * @param createDate the value for gallery_channel.CREATE_DATE
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery_channel.CREATE_TIME
     *
     * @return the value of gallery_channel.CREATE_TIME
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery_channel.CREATE_TIME
     *
     * @param createTime the value for gallery_channel.CREATE_TIME
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery_channel.COMPANY_ID
     *
     * @return the value of gallery_channel.COMPANY_ID
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery_channel.COMPANY_ID
     *
     * @param companyId the value for gallery_channel.COMPANY_ID
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery_channel.BRANCH_ID
     *
     * @return the value of gallery_channel.BRANCH_ID
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery_channel.BRANCH_ID
     *
     * @param branchId the value for gallery_channel.BRANCH_ID
     * @mbggenerated Wed Sep 19 10:35:12 CST 2018
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }
}