package com.ruoyi.content.domain;

import java.util.Date;

public class LdCom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.COMCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String comcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.OUTCOMCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String outcomcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.NAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.SHORTNAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.ADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.ZIPCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.PHONE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.FAX
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.EMAIL
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.WEBADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String webaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.SATRAPNAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String satrapname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.INSUMONITORCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String insumonitorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.INSUREID
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String insureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.SIGNID
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String signid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.REGIONALISMCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String regionalismcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.COMNATURE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String comnature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.VALIDCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String validcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.SIGN
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.COMCITYSIZE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String comcitysize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.SERVICENAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String servicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.SERVICENO
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String serviceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.SERVICEPHONE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String servicephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.SERVICEPOSTADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String servicepostaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.SERVICEPOSTZIPCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String servicepostzipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.LETTERSERVICENAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String letterservicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.LETTERSERVICENO
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String letterserviceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.LETTERSERVICEPHONE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String letterservicephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.LETTERSERVICEPOSTADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String letterservicepostaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.LETTERSERVICEPOSTZIPCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String letterservicepostzipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.COMGRADE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String comgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.COMAREATYPE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String comareatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.INPUTDATE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private Date inputdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.INPUTTIME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String inputtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.SEQUENCE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.PROVINCE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.CITY
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.COUNTY
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcom.PREFECTURALLEVELCITY
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    private String prefecturallevelcity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.COMCODE
     *
     * @return the value of ldcom.COMCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getComcode() {
        return comcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.COMCODE
     *
     * @param comcode the value for ldcom.COMCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setComcode(String comcode) {
        this.comcode = comcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.OUTCOMCODE
     *
     * @return the value of ldcom.OUTCOMCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getOutcomcode() {
        return outcomcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.OUTCOMCODE
     *
     * @param outcomcode the value for ldcom.OUTCOMCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setOutcomcode(String outcomcode) {
        this.outcomcode = outcomcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.NAME
     *
     * @return the value of ldcom.NAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.NAME
     *
     * @param name the value for ldcom.NAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.SHORTNAME
     *
     * @return the value of ldcom.SHORTNAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.SHORTNAME
     *
     * @param shortname the value for ldcom.SHORTNAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.ADDRESS
     *
     * @return the value of ldcom.ADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.ADDRESS
     *
     * @param address the value for ldcom.ADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.ZIPCODE
     *
     * @return the value of ldcom.ZIPCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.ZIPCODE
     *
     * @param zipcode the value for ldcom.ZIPCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.PHONE
     *
     * @return the value of ldcom.PHONE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.PHONE
     *
     * @param phone the value for ldcom.PHONE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.FAX
     *
     * @return the value of ldcom.FAX
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.FAX
     *
     * @param fax the value for ldcom.FAX
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.EMAIL
     *
     * @return the value of ldcom.EMAIL
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.EMAIL
     *
     * @param email the value for ldcom.EMAIL
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.WEBADDRESS
     *
     * @return the value of ldcom.WEBADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getWebaddress() {
        return webaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.WEBADDRESS
     *
     * @param webaddress the value for ldcom.WEBADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setWebaddress(String webaddress) {
        this.webaddress = webaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.SATRAPNAME
     *
     * @return the value of ldcom.SATRAPNAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getSatrapname() {
        return satrapname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.SATRAPNAME
     *
     * @param satrapname the value for ldcom.SATRAPNAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setSatrapname(String satrapname) {
        this.satrapname = satrapname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.INSUMONITORCODE
     *
     * @return the value of ldcom.INSUMONITORCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getInsumonitorcode() {
        return insumonitorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.INSUMONITORCODE
     *
     * @param insumonitorcode the value for ldcom.INSUMONITORCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setInsumonitorcode(String insumonitorcode) {
        this.insumonitorcode = insumonitorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.INSUREID
     *
     * @return the value of ldcom.INSUREID
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getInsureid() {
        return insureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.INSUREID
     *
     * @param insureid the value for ldcom.INSUREID
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setInsureid(String insureid) {
        this.insureid = insureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.SIGNID
     *
     * @return the value of ldcom.SIGNID
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getSignid() {
        return signid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.SIGNID
     *
     * @param signid the value for ldcom.SIGNID
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setSignid(String signid) {
        this.signid = signid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.REGIONALISMCODE
     *
     * @return the value of ldcom.REGIONALISMCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getRegionalismcode() {
        return regionalismcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.REGIONALISMCODE
     *
     * @param regionalismcode the value for ldcom.REGIONALISMCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setRegionalismcode(String regionalismcode) {
        this.regionalismcode = regionalismcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.COMNATURE
     *
     * @return the value of ldcom.COMNATURE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getComnature() {
        return comnature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.COMNATURE
     *
     * @param comnature the value for ldcom.COMNATURE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setComnature(String comnature) {
        this.comnature = comnature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.VALIDCODE
     *
     * @return the value of ldcom.VALIDCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getValidcode() {
        return validcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.VALIDCODE
     *
     * @param validcode the value for ldcom.VALIDCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setValidcode(String validcode) {
        this.validcode = validcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.SIGN
     *
     * @return the value of ldcom.SIGN
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.SIGN
     *
     * @param sign the value for ldcom.SIGN
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.COMCITYSIZE
     *
     * @return the value of ldcom.COMCITYSIZE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getComcitysize() {
        return comcitysize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.COMCITYSIZE
     *
     * @param comcitysize the value for ldcom.COMCITYSIZE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setComcitysize(String comcitysize) {
        this.comcitysize = comcitysize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.SERVICENAME
     *
     * @return the value of ldcom.SERVICENAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getServicename() {
        return servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.SERVICENAME
     *
     * @param servicename the value for ldcom.SERVICENAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setServicename(String servicename) {
        this.servicename = servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.SERVICENO
     *
     * @return the value of ldcom.SERVICENO
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getServiceno() {
        return serviceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.SERVICENO
     *
     * @param serviceno the value for ldcom.SERVICENO
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setServiceno(String serviceno) {
        this.serviceno = serviceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.SERVICEPHONE
     *
     * @return the value of ldcom.SERVICEPHONE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getServicephone() {
        return servicephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.SERVICEPHONE
     *
     * @param servicephone the value for ldcom.SERVICEPHONE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setServicephone(String servicephone) {
        this.servicephone = servicephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.SERVICEPOSTADDRESS
     *
     * @return the value of ldcom.SERVICEPOSTADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getServicepostaddress() {
        return servicepostaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.SERVICEPOSTADDRESS
     *
     * @param servicepostaddress the value for ldcom.SERVICEPOSTADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setServicepostaddress(String servicepostaddress) {
        this.servicepostaddress = servicepostaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.SERVICEPOSTZIPCODE
     *
     * @return the value of ldcom.SERVICEPOSTZIPCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getServicepostzipcode() {
        return servicepostzipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.SERVICEPOSTZIPCODE
     *
     * @param servicepostzipcode the value for ldcom.SERVICEPOSTZIPCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setServicepostzipcode(String servicepostzipcode) {
        this.servicepostzipcode = servicepostzipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.LETTERSERVICENAME
     *
     * @return the value of ldcom.LETTERSERVICENAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getLetterservicename() {
        return letterservicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.LETTERSERVICENAME
     *
     * @param letterservicename the value for ldcom.LETTERSERVICENAME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setLetterservicename(String letterservicename) {
        this.letterservicename = letterservicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.LETTERSERVICENO
     *
     * @return the value of ldcom.LETTERSERVICENO
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getLetterserviceno() {
        return letterserviceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.LETTERSERVICENO
     *
     * @param letterserviceno the value for ldcom.LETTERSERVICENO
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setLetterserviceno(String letterserviceno) {
        this.letterserviceno = letterserviceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.LETTERSERVICEPHONE
     *
     * @return the value of ldcom.LETTERSERVICEPHONE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getLetterservicephone() {
        return letterservicephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.LETTERSERVICEPHONE
     *
     * @param letterservicephone the value for ldcom.LETTERSERVICEPHONE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setLetterservicephone(String letterservicephone) {
        this.letterservicephone = letterservicephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.LETTERSERVICEPOSTADDRESS
     *
     * @return the value of ldcom.LETTERSERVICEPOSTADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getLetterservicepostaddress() {
        return letterservicepostaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.LETTERSERVICEPOSTADDRESS
     *
     * @param letterservicepostaddress the value for ldcom.LETTERSERVICEPOSTADDRESS
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setLetterservicepostaddress(String letterservicepostaddress) {
        this.letterservicepostaddress = letterservicepostaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.LETTERSERVICEPOSTZIPCODE
     *
     * @return the value of ldcom.LETTERSERVICEPOSTZIPCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getLetterservicepostzipcode() {
        return letterservicepostzipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.LETTERSERVICEPOSTZIPCODE
     *
     * @param letterservicepostzipcode the value for ldcom.LETTERSERVICEPOSTZIPCODE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setLetterservicepostzipcode(String letterservicepostzipcode) {
        this.letterservicepostzipcode = letterservicepostzipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.COMGRADE
     *
     * @return the value of ldcom.COMGRADE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getComgrade() {
        return comgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.COMGRADE
     *
     * @param comgrade the value for ldcom.COMGRADE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setComgrade(String comgrade) {
        this.comgrade = comgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.COMAREATYPE
     *
     * @return the value of ldcom.COMAREATYPE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getComareatype() {
        return comareatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.COMAREATYPE
     *
     * @param comareatype the value for ldcom.COMAREATYPE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setComareatype(String comareatype) {
        this.comareatype = comareatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.INPUTDATE
     *
     * @return the value of ldcom.INPUTDATE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public Date getInputdate() {
        return inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.INPUTDATE
     *
     * @param inputdate the value for ldcom.INPUTDATE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.INPUTTIME
     *
     * @return the value of ldcom.INPUTTIME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.INPUTTIME
     *
     * @param inputtime the value for ldcom.INPUTTIME
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setInputtime(String inputtime) {
        this.inputtime = inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.SEQUENCE
     *
     * @return the value of ldcom.SEQUENCE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.SEQUENCE
     *
     * @param sequence the value for ldcom.SEQUENCE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.PROVINCE
     *
     * @return the value of ldcom.PROVINCE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.PROVINCE
     *
     * @param province the value for ldcom.PROVINCE
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.CITY
     *
     * @return the value of ldcom.CITY
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.CITY
     *
     * @param city the value for ldcom.CITY
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.COUNTY
     *
     * @return the value of ldcom.COUNTY
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.COUNTY
     *
     * @param county the value for ldcom.COUNTY
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcom.PREFECTURALLEVELCITY
     *
     * @return the value of ldcom.PREFECTURALLEVELCITY
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public String getPrefecturallevelcity() {
        return prefecturallevelcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcom.PREFECTURALLEVELCITY
     *
     * @param prefecturallevelcity the value for ldcom.PREFECTURALLEVELCITY
     *
     * @mbggenerated Tue Jul 24 14:14:03 CST 2018
     */
    public void setPrefecturallevelcity(String prefecturallevelcity) {
        this.prefecturallevelcity = prefecturallevelcity;
    }
}