package com.ruoyi.content.domain;

public class PicAdInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.PIC_AD_ID
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private Integer picAdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.PIC_AD_TYPE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String picAdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.PIC_AD_TITLE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String picAdTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.PIC_AD_NAME
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String picAdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.PIC_AD_URL
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String picAdUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.PIC_AD_STATE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String picAdState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.COMPANY_ID
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.CREATE_DATE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.CREATE_TIME
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.CREATE_USER
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.UPDATE_USER
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.UPDATE_DATE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_ad_info.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.PIC_AD_ID
     *
     * @return the value of pic_ad_info.PIC_AD_ID
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public Integer getPicAdId() {
        return picAdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.PIC_AD_ID
     *
     * @param picAdId the value for pic_ad_info.PIC_AD_ID
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setPicAdId(Integer picAdId) {
        this.picAdId = picAdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.PIC_AD_TYPE
     *
     * @return the value of pic_ad_info.PIC_AD_TYPE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getPicAdType() {
        return picAdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.PIC_AD_TYPE
     *
     * @param picAdType the value for pic_ad_info.PIC_AD_TYPE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setPicAdType(String picAdType) {
        this.picAdType = picAdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.PIC_AD_TITLE
     *
     * @return the value of pic_ad_info.PIC_AD_TITLE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getPicAdTitle() {
        return picAdTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.PIC_AD_TITLE
     *
     * @param picAdTitle the value for pic_ad_info.PIC_AD_TITLE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setPicAdTitle(String picAdTitle) {
        this.picAdTitle = picAdTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.PIC_AD_NAME
     *
     * @return the value of pic_ad_info.PIC_AD_NAME
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getPicAdName() {
        return picAdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.PIC_AD_NAME
     *
     * @param picAdName the value for pic_ad_info.PIC_AD_NAME
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setPicAdName(String picAdName) {
        this.picAdName = picAdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.PIC_AD_URL
     *
     * @return the value of pic_ad_info.PIC_AD_URL
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getPicAdUrl() {
        return picAdUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.PIC_AD_URL
     *
     * @param picAdUrl the value for pic_ad_info.PIC_AD_URL
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setPicAdUrl(String picAdUrl) {
        this.picAdUrl = picAdUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.PIC_AD_STATE
     *
     * @return the value of pic_ad_info.PIC_AD_STATE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getPicAdState() {
        return picAdState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.PIC_AD_STATE
     *
     * @param picAdState the value for pic_ad_info.PIC_AD_STATE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setPicAdState(String picAdState) {
        this.picAdState = picAdState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.COMPANY_ID
     *
     * @return the value of pic_ad_info.COMPANY_ID
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.COMPANY_ID
     *
     * @param companyId the value for pic_ad_info.COMPANY_ID
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.CREATE_DATE
     *
     * @return the value of pic_ad_info.CREATE_DATE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.CREATE_DATE
     *
     * @param createDate the value for pic_ad_info.CREATE_DATE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.CREATE_TIME
     *
     * @return the value of pic_ad_info.CREATE_TIME
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.CREATE_TIME
     *
     * @param createTime the value for pic_ad_info.CREATE_TIME
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.CREATE_USER
     *
     * @return the value of pic_ad_info.CREATE_USER
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.CREATE_USER
     *
     * @param createUser the value for pic_ad_info.CREATE_USER
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.UPDATE_USER
     *
     * @return the value of pic_ad_info.UPDATE_USER
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.UPDATE_USER
     *
     * @param updateUser the value for pic_ad_info.UPDATE_USER
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.UPDATE_DATE
     *
     * @return the value of pic_ad_info.UPDATE_DATE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.UPDATE_DATE
     *
     * @param updateDate the value for pic_ad_info.UPDATE_DATE
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_ad_info.UPDATE_TIME
     *
     * @return the value of pic_ad_info.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_ad_info.UPDATE_TIME
     *
     * @param updateTime the value for pic_ad_info.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 12 09:41:05 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}