package com.ruoyi.content.domain;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_ID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.OPENID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.HEAD_IMG_URL
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String headImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.NICK_NAME
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.COMPANY_ID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.AGENT_CODE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String agentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_NAME
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ID_TYPE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ID_NO
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.GENDER
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_POSITION
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String userPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.BIRTHDAY
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.EDUCATION
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.MOBILE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_EMAIL
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.PROVINCE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.CITY
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.AREA
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.REFEREE_USERID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String refereeUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.STATE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.CREATE_USER
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.CREATE_TIME
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.UPDATE_TIME
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.UPDATE_REMARK
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String updateRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.SOURCE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.TIMESTAMP
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
//    private String timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.AGE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
//    private String age;
    private String cardImgUrl;

    public String getCardImgUrl() {
		return cardImgUrl;
	}

	public void setCardImgUrl(String cardImgUrl) {
		this.cardImgUrl = cardImgUrl;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_ID
     *
     * @return the value of user_info.USER_ID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_ID
     *
     * @param userId the value for user_info.USER_ID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.OPENID
     *
     * @return the value of user_info.OPENID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.OPENID
     *
     * @param openid the value for user_info.OPENID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.HEAD_IMG_URL
     *
     * @return the value of user_info.HEAD_IMG_URL
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.HEAD_IMG_URL
     *
     * @param headImgUrl the value for user_info.HEAD_IMG_URL
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.NICK_NAME
     *
     * @return the value of user_info.NICK_NAME
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.NICK_NAME
     *
     * @param nickName the value for user_info.NICK_NAME
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.COMPANY_ID
     *
     * @return the value of user_info.COMPANY_ID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.COMPANY_ID
     *
     * @param companyId the value for user_info.COMPANY_ID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.AGENT_CODE
     *
     * @return the value of user_info.AGENT_CODE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getAgentCode() {
        return agentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.AGENT_CODE
     *
     * @param agentCode the value for user_info.AGENT_CODE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_NAME
     *
     * @return the value of user_info.USER_NAME
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_NAME
     *
     * @param userName the value for user_info.USER_NAME
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ID_TYPE
     *
     * @return the value of user_info.ID_TYPE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ID_TYPE
     *
     * @param idType the value for user_info.ID_TYPE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setIdType(String idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ID_NO
     *
     * @return the value of user_info.ID_NO
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ID_NO
     *
     * @param idNo the value for user_info.ID_NO
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.GENDER
     *
     * @return the value of user_info.GENDER
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.GENDER
     *
     * @param gender the value for user_info.GENDER
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_POSITION
     *
     * @return the value of user_info.USER_POSITION
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getUserPosition() {
        return userPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_POSITION
     *
     * @param userPosition the value for user_info.USER_POSITION
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setUserPosition(String userPosition) {
        this.userPosition = userPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.BIRTHDAY
     *
     * @return the value of user_info.BIRTHDAY
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.BIRTHDAY
     *
     * @param birthday the value for user_info.BIRTHDAY
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.EDUCATION
     *
     * @return the value of user_info.EDUCATION
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.EDUCATION
     *
     * @param education the value for user_info.EDUCATION
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.MOBILE
     *
     * @return the value of user_info.MOBILE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.MOBILE
     *
     * @param mobile the value for user_info.MOBILE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_EMAIL
     *
     * @return the value of user_info.USER_EMAIL
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_EMAIL
     *
     * @param userEmail the value for user_info.USER_EMAIL
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.PROVINCE
     *
     * @return the value of user_info.PROVINCE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.PROVINCE
     *
     * @param province the value for user_info.PROVINCE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.CITY
     *
     * @return the value of user_info.CITY
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.CITY
     *
     * @param city the value for user_info.CITY
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.AREA
     *
     * @return the value of user_info.AREA
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.AREA
     *
     * @param area the value for user_info.AREA
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.REFEREE_USERID
     *
     * @return the value of user_info.REFEREE_USERID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getRefereeUserid() {
        return refereeUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.REFEREE_USERID
     *
     * @param refereeUserid the value for user_info.REFEREE_USERID
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setRefereeUserid(String refereeUserid) {
        this.refereeUserid = refereeUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.STATE
     *
     * @return the value of user_info.STATE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.STATE
     *
     * @param state the value for user_info.STATE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.CREATE_USER
     *
     * @return the value of user_info.CREATE_USER
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.CREATE_USER
     *
     * @param createUser the value for user_info.CREATE_USER
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.CREATE_TIME
     *
     * @return the value of user_info.CREATE_TIME
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.UPDATE_REMARK
     *
     * @return the value of user_info.UPDATE_REMARK
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getUpdateRemark() {
        return updateRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.UPDATE_REMARK
     *
     * @param updateRemark the value for user_info.UPDATE_REMARK
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setUpdateRemark(String updateRemark) {
        this.updateRemark = updateRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.SOURCE
     *
     * @return the value of user_info.SOURCE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.SOURCE
     *
     * @param source the value for user_info.SOURCE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.TIMESTAMP
     *
     * @return the value of user_info.TIMESTAMP
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.AGE
     *
     * @return the value of user_info.AGE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
//    public String getAge() {
//        return age;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.AGE
     *
     * @param age the value for user_info.AGE
     *
     * @mbggenerated Tue Jul 16 10:12:10 CST 2019
     */
//    public void setAge(String age) {
//        this.age = age;
//    }

	public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

//	public String getTimestamp() {
//		return timestamp;
//	}
//
//	public void setTimestamp(String timestamp) {
//		this.timestamp = timestamp;
//	}

	@Override
	public String toString() {
		return "UserInfo [userId=" + userId + ", openid=" + openid + ", headImgUrl=" + headImgUrl + ", nickName="
				+ nickName + ", companyId=" + companyId + ", agentCode=" + agentCode + ", userName=" + userName
				+ ", idType=" + idType + ", idNo=" + idNo + ", gender=" + gender + ", userPosition=" + userPosition
				+ ", birthday=" + birthday + ", education=" + education + ", mobile=" + mobile + ", userEmail="
				+ userEmail + ", province=" + province + ", city=" + city + ", area=" + area + ", refereeUserid="
				+ refereeUserid + ", state=" + state + ", createUser=" + createUser + ", createTime=" + createTime
				+ ", updateTime=" + updateTime + ", updateRemark=" + updateRemark + ", source=" + source
				+ "]";//, timestamp=" + timestamp + ", age=" + age + "]";
	}
    
}